/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * OpenBridge.me API
 * This is the OpenBridge.me client API. It is used to interact with the OpenBridge.me platform. For specific APIs we recommend using their respective documentation.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { Balance } from "../../model";
import { customInstance } from "../../../services/custom-axios-instance";
import type { ErrorType } from "../../../services/custom-axios-instance";

export const clientBalanceList = (signal?: AbortSignal) => {
  return customInstance<Balance[]>({
    url: `/api/client-balance/`,
    method: "GET",
    signal,
  });
};

export const getClientBalanceListQueryKey = () => {
  return [`/api/client-balance/`] as const;
};

export const getClientBalanceListQueryOptions = <
  TData = Awaited<ReturnType<typeof clientBalanceList>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof clientBalanceList>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getClientBalanceListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof clientBalanceList>>
  > = ({ signal }) => clientBalanceList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof clientBalanceList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ClientBalanceListQueryResult = NonNullable<
  Awaited<ReturnType<typeof clientBalanceList>>
>;
export type ClientBalanceListQueryError = ErrorType<unknown>;

export const useClientBalanceList = <
  TData = Awaited<ReturnType<typeof clientBalanceList>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof clientBalanceList>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getClientBalanceListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
