# Generated by Django 4.2.10 on 2024-04-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openbridge.helpers
import openbridge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_provider', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=200)),
                ('url_compatible_name', models.CharField(max_length=100, unique=True, validators=[openbridge.models.is_alphanumeric])),
                ('image', models.URLField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regex', models.CharField(max_length=200, validators=[openbridge.helpers.regex_validator])),
                ('price_per', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('rule_level', models.IntegerField(default=0)),
                ('api_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbridge.apiservice')),
            ],
        ),
        migrations.CreateModel(
            name='UserBills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('bill_type', models.CharField(choices=[('DAY', 'Daily'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=10)),
                ('billing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbridge.billingrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('api_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='openbridge.apiservice')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Service's API key",
                'verbose_name_plural': "Service's API keys",
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField(null=True)),
                ('ip', models.CharField(max_length=100, null=True)),
                ('user_agent', models.TextField(null=True)),
                ('method', models.CharField(max_length=10, null=True)),
                ('details', models.TextField(null=True)),
                ('api_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbridge.apiservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
