# Generated by Django 4.2.10 on 2024-02-15 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openbridge.helpers
import openbridge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_provider', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=200)),
                ('url_compatible_name', models.CharField(max_length=100, unique=True, validators=[openbridge.models.is_alphanumeric])),
                ('image', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regex', models.CharField(max_length=200, validators=[openbridge.helpers.regex_validator])),
                ('price_per', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('rule_level', models.IntegerField(default=0)),
                ('api_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbridge.apiservice')),
            ],
        ),
        migrations.CreateModel(
            name='UserBills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('bill_type', models.CharField(choices=[('DAY', 'Daily'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=10)),
                ('billing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbridge.billingrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_path', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('api_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbridge.apiservice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
