# Generated by Django 4.2.10 on 2024-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbills',
            name='billing_rule',
        ),
        migrations.RemoveField(
            model_name='userbills',
            name='total',
        ),
        migrations.AlterField(
            model_name='userbills',
            name='bill_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10),
        ),
    ]
