# Generated by Django 4.2.10 on 2024-02-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiservice',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
