# Generated by Django 4.2.10 on 2024-02-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0002_alter_apiservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OrganizationAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('api_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='openbridge.apiservice')),
            ],
            options={
                'verbose_name': "API Service's key",
                'verbose_name_plural': "API Service's keys",
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
