# Generated by Django 4.2.10 on 2024-05-02 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openbridge.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbridge', '0002_remove_userbills_billing_rule_remove_userbills_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debit', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='billingrule',
            name='regex',
            field=models.CharField(max_length=200, validators=[openbridge.models.regex_validator]),
        ),
        migrations.DeleteModel(
            name='UserBills',
        ),
    ]
