# Generated by Django 4.2.10 on 2024-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0003_userledger_alter_billingrule_regex_delete_userbills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userledger',
            name='billing_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userledger',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
