# Generated by Django 4.2.10 on 2024-02-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0003_apiservice_active_organizationapikey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationAPIKey',
            new_name='ServiceAPIKey',
        ),
    ]
