# Generated by Django 4.2.10 on 2024-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0004_rename_organizationapikey_serviceapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceapikey',
            options={'ordering': ('-created',), 'verbose_name': "Service's API key", 'verbose_name_plural': "Service's API keys"},
        ),
        migrations.RenameField(
            model_name='apirequest',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='apirequest',
            name='request_path',
        ),
        migrations.AddField(
            model_name='apirequest',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='user_agent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
