# Generated by Django 4.2.10 on 2024-05-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0004_userledger_billing_period_userledger_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userledger',
            name='description',
        ),
        migrations.AddField(
            model_name='userledger',
            name='api_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openbridge.apiservice'),
        ),
        migrations.AlterField(
            model_name='userledger',
            name='billing_period',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
