# Generated by Django 4.2.10 on 2024-02-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbridge', '0008_alter_serviceapikey_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequest',
            name='status_code',
        ),
    ]
