/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * OpenBridge.me API
 * This is the OpenBridge.me client API. It is used to interact with the OpenBridge.me platform. For specific APIs we recommend using their respective documentation.
 * OpenAPI spec version: 1.0.0
 */

export interface APIService {
  active?: boolean;
  api_key?: string;
  readonly created_at: string;
  description: string;
  readonly id: number;
  /**
   * @maxLength 200
   * @nullable
   */
  image?: string | null;
  /** @maxLength 200 */
  name: string;
  /** @maxLength 200 */
  service_provider: string;
  readonly updated_at: string;
  /** @maxLength 200 */
  url: string;
  /** @maxLength 100 */
  url_compatible_name: string;
}
