/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * OpenBridge.me API
 * This is the OpenBridge.me client API. It is used to interact with the OpenBridge.me platform. For specific APIs we recommend using their respective documentation.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedBillingRule {
  api_service?: number;
  readonly created_at?: string;
  description?: string;
  readonly id?: number;
  /** @maxLength 200 */
  name?: string;
  /** @pattern ^-?\d{0,5}(?:\.\d{0,5})?$ */
  price_per?: string;
  /** @maxLength 200 */
  regex?: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  rule_level?: number;
  readonly updated_at?: string;
}
