/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * OpenBridge.me API
 * This is the OpenBridge.me client API. It is used to interact with the OpenBridge.me platform. For specific APIs we recommend using their respective documentation.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedServiceAPIKey {
  api_service?: number;
  readonly created?: string;
  readonly id?: string;
  /**
   * A free-form name for the API key. Need not be unique. 50 characters max.
   * @maxLength 50
   */
  name?: string;
  readonly prefix?: string;
  /** If the API key is revoked, clients cannot use it anymore. (This cannot be undone.) */
  revoked?: boolean;
}
