/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * OpenBridge.me API
 * This is the OpenBridge.me client API. It is used to interact with the OpenBridge.me platform. For specific APIs we recommend using their respective documentation.
 * OpenAPI spec version: 1.0.0
 */
import type { APIServiceMinimal } from "./aPIServiceMinimal";

export interface UserLedger {
  api_service: APIServiceMinimal;
  /** @nullable */
  billing_period?: string | null;
  readonly created_at: string;
  /** @pattern ^-?\d{0,5}(?:\.\d{0,5})?$ */
  credit?: string;
  /** @pattern ^-?\d{0,5}(?:\.\d{0,5})?$ */
  debit?: string;
  /** @nullable */
  description?: string | null;
  readonly id: number;
  user: number;
}
